package org.cce.sistema.model;
// Generated 6/01/2021 08:24:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parroquia generated by hbm2java
 */
public class Parroquia  implements java.io.Serializable {


     private Integer idParroquia;
     private String lugar;
     private Set catequizados = new HashSet(0);

    public Parroquia() {
    }

    public Parroquia(String lugar, Set catequizados) {
       this.lugar = lugar;
       this.catequizados = catequizados;
    }
   
    public Integer getIdParroquia() {
        return this.idParroquia;
    }
    
    public void setIdParroquia(Integer idParroquia) {
        this.idParroquia = idParroquia;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getCatequizados() {
        return this.catequizados;
    }
    
    public void setCatequizados(Set catequizados) {
        this.catequizados = catequizados;
    }




}


