package org.cce.sistema.model;
// Generated 6/01/2021 08:24:23 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Porcentaje generated by hbm2java
 */
public class Porcentaje implements java.io.Serializable {

    private Integer idPorcentaje;
    private Long misa;
    private Long tareas;
    private Long extras;
    private Long catequesis;
    private Long asistencia;
    private Long evaluacion;
    private String descripcion;
    private Integer dias;
    private Long puntualidad;
    private Long conducta;
    private Set registros = new HashSet(0);

    public Porcentaje() {
    }

    public Porcentaje(Integer idPorcentaje, Long misa, Long tareas, Long extras, Long catequesis, Long asistencia, Long evaluacion, String descripcion, Integer dias, Long puntualidad, Long conducta) {
        this.idPorcentaje = idPorcentaje;
        this.misa = misa;
        this.tareas = tareas;
        this.extras = extras;
        this.catequesis = catequesis;
        this.asistencia = asistencia;
        this.evaluacion = evaluacion;
        this.descripcion = descripcion;
        this.dias = dias;
        this.puntualidad = puntualidad;
        this.conducta = conducta;
    }

    public Integer getIdPorcentaje() {
        return idPorcentaje;
    }

    public void setIdPorcentaje(Integer idPorcentaje) {
        this.idPorcentaje = idPorcentaje;
    }

    public Long getMisa() {
        return misa;
    }

    public void setMisa(Long misa) {
        this.misa = misa;
    }

    public Long getTareas() {
        return tareas;
    }

    public void setTareas(Long tareas) {
        this.tareas = tareas;
    }

    public Long getExtras() {
        return extras;
    }

    public void setExtras(Long extras) {
        this.extras = extras;
    }

    public Long getCatequesis() {
        return catequesis;
    }

    public void setCatequesis(Long catequesis) {
        this.catequesis = catequesis;
    }

    public Long getAsistencia() {
        return asistencia;
    }

    public void setAsistencia(Long asistencia) {
        this.asistencia = asistencia;
    }

    public Long getEvaluacion() {
        return evaluacion;
    }

    public void setEvaluacion(Long evaluacion) {
        this.evaluacion = evaluacion;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getDias() {
        return dias;
    }

    public void setDias(Integer dias) {
        this.dias = dias;
    }

    public Long getPuntualidad() {
        return puntualidad;
    }

    public void setPuntualidad(Long puntualidad) {
        this.puntualidad = puntualidad;
    }

    public Long getConducta() {
        return conducta;
    }

    public void setConducta(Long conducta) {
        this.conducta = conducta;
    }

    public Set getRegistros() {
        return registros;
    }

    public void setRegistros(Set registros) {
        this.registros = registros;
    }

}
